### ISSUE TITLE
A suggestion on command block tools

### ISSUE THREAD

**Issue by ColdNSs** [nonamecrackers2/crackers-wither-storm-mod#102]
Make it so that command block tools can break real command blocks
It is unnecessary but it does make sense
Also please make it configurable whether a survival player can break command blocks with command block tools and how long it takes

**Comment by nonamecrackers2** [comment]
Survival players can't place command blocks, and can't even use them after they've acquired them. I also don't think it's possible without unnecessarily modifying the game code to make this possible. Because you can't use them, and they are intended to be unbreakable, we should probably keep it that way.
