### ISSUE TITLE
Phases 6-7 makes weather thundering (cant change)

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#1039]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
when the WS reaches phase6-7, make it THUNDER AND RAIN! ⛈️⚡⚡⚡⛈️⛈️

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Pandaboi25x** [comment]
i think the (cant change) should be (can change) i mean some players hate rain and thunder and it would really annoy them tho cool idea

**Comment by V0calgiant12** [comment]
This can be done very easily with a small datapack

**Comment by myron-obsolete-account** [comment]
> _**Please read the guidelines before submitting:**_ #217
> 
> **Description of feature** when the WS reaches phase6-7, make it THUNDER AND RAIN! ⛈️⚡⚡⚡⛈️⛈️
> 
> **ONLY ONE FEATURE REQUEST PER ISSUE**

bro uses so many emojis for dramatic effect

**Comment by humzahre** [comment]
> This can be done very easily with a small datapack

BRUH INSTALLING DATA PACKS IS HARD BTW IT OnLY FOR 1 WORLD

**Comment by V0calgiant12** [comment]
No they aren't, and there are mods out there that let you automatically have a datapack enabled on every world. In order to install a datapack, you can either click the Data Packs button, open folder, copy and paste the datapack in there, then create the world. And you can still add them to an existing world by opening the world folder, going to the datapacks folder, and copy and pasting it there.

**Comment by V0calgiant12** [comment]
No they aren't, and there are mods out there that let you automatically have a datapack enabled on every world. In order to install a datapack, you can either click the Data Packs button, open folder, copy and paste the datapack in there, then create the world. And you can still add them to an existing world by opening the world folder, going to the datapacks folder, and copy and pasting it there.

**Comment by NinjaSam5399** [comment]
This is the best data pack, so your suggestion will may be added in this datapack. Datapack: https://www.curseforge.com/minecraft/texture-packs/bwsb-better-wither-storm-bowels-and-more.

**Comment by humzahre** [comment]
does it have to be a zip?

**Comment by myron-obsolete-account** [comment]
guess what no

**Comment by WitherBean** [comment]
In the datapack, when it goes into phase 7 it thunders.

**Comment by humzahre** [comment]
but what about phase 6

**Comment by WitherBean** [comment]
Six will not thunder, but I can change that.

**Comment by humzahre** [comment]
ok

**Comment by nonamecrackers2** [comment]
Pretty much #228. I've outlined my opinion on changing the weather/weather effects there.
