### ISSUE TITLE
Epic Upgrade on the Crackers Wither Storm Mod: Climb on top of the Wither Storm just like on the Shulkers!

### ISSUE THREAD

**Issue by TheSrBig** [nonamecrackers2/crackers-wither-storm-mod#1062]
Players are currently unable to stand on the Withered Storm when it enlarges in Crackers Wither Storm Mod. Implementing a feature comparable to Shulkers in Minecraft, allowing players to step on them despite being creatures, would be intriguing and difficult.

Despite being creatures in the game, shulkers have a special mechanism that makes interacting with them more engaging. Shulkers provide a more complete gameplay experience as players can parry them and use them to move around the landscape rather than just being an adversary to beat.

Given this, allowing players to stand on Wither Storm in the mod would be both exciting and difficult, especially as it grows. Players would have a more memorable and rewarding experience as a result of this added layer of strategy and enjoyment in taking on this terrifying beast.

We are aware that some people may have doubts about the feasibility of integrating such a system, but we think it is doable, especially considering that Shulkers has already been implemented in the game as a precedent. The developers could study the mechanics of the Shulkers and adapt it for the Wither Storm, allowing players to interact with it in a similar way.

**Comment by Bloxxify1520** [comment]
This looks like it was used with ChatGPT lmaooo

**Comment by TheSrBig** [comment]
> This looks like it was used with ChatGPT lmaooo

?

**Comment by Globalfirestorm10** [comment]
> This looks like it was used with ChatGPT lmaooo

Yeah, it does

**Comment by Globalfirestorm10** [comment]
> Players are currently unable to stand on the Withered Storm when it enlarges in Crackers Wither Storm Mod. Implementing a feature comparable to Shulkers in Minecraft, allowing players to step on them despite being creatures, would be intriguing and difficult.
> 
> 
> 
> Despite being creatures in the game, shulkers have a special mechanism that makes interacting with them more engaging. Shulkers provide a more complete gameplay experience as players can parry them and use them to move around the landscape rather than just being an adversary to beat.
> 
> 
> 
> Given this, allowing players to stand on Wither Storm in the mod would be both exciting and difficult, especially as it grows. Players would have a more memorable and rewarding experience as a result of this added layer of strategy and enjoyment in taking on this terrifying beast.
> 
> 
> 
> We are aware that some people may have doubts about the feasibility of integrating such a system, but we think it is doable, especially considering that Shulkers has already been implemented in the game as a precedent. The developers could study the mechanics of the Shulkers and adapt it for the Wither Storm, allowing players to interact with it in a similar way.

Idk if this would be feasible or not

**Comment by Bloxxify1520** [comment]
If they went with this approach, he would have to do either 2 options:

Make one LARGE hitbox that covers the entire storm, in a cube shape. So when you get NEAR the storm, you collide with it

Make ALOT of entities with collisions that are in the same shape as the storm, causing alot of lag in later stages

**Comment by Globalfirestorm10** [comment]
Both of these would hit performance, and the one large hit box would mean you could walk on air. So again, I doubt this would be a good feature, but I'll leave it to cracker

**Comment by WitherBean** [comment]
I believe somebody already suggested this.

**Comment by myron-obsolete-account** [comment]
> I believe somebody already suggested this.

Yes indeed, #494.

Also, making this would be kinda impossible, and you can't make it "just like on the Shulkers". The shulker is a cube-shaped (literally a cube) organism, and Minecraft hitboxes are cuboidly shaped too. Now what they did was just simply make the hitbox as large as a 1x1x1m cube, and put it directly over the Skulker and added an option that this hitbox is a solid surface instead of a "running-into-it-will-push-you-back" surface. When you do that on the Wither Storm, the same thing will happen: cube hitbox would make unlogical collision borders to the body of the storm, plus, when it rotates the hitbox ain't even rotating with it. If you noticed, the Wither Storm already has more than 1 hitbox in later-than-phase-5-phases:

One large hitbox would make the collisions with the storm too big. But thousands of hitboxes realigned to the shape of the storms body would, at best, crash your game. At worst, your PC might would've exploded (little joke here).

Constructive criticism is important, so I decided to waste 5 minutes of my lifetime here. Have a nice rest of your day.

**Comment by darkheart78** [comment]
maybe in the future

**Comment by Isoknight** [comment]
> I believe somebody already suggested this.

It was requested by the same guy, for some reason he made another one.
