### ISSUE TITLE
Harder Symbiont

### ISSUE THREAD

**Issue by darkheart78** [nonamecrackers2/crackers-wither-storm-mod#1103]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**
I think the withered symbiont fight could be harder. If you have a diamond sword you can beat them easily. Cooldown for attacking the back so you cant combo and kill it immediatly. 

Ideas to make it harder

1.  Cooldown for attacking the back so you cant combo and kill it immediatly. 
2. wither storm does some more stuff during fight like shooting fireballs.
3. maybe withered symbiont spawned phases 5-7 could be harder and bigger.
4. more health cause it dies easily
5. skeletons shoot the back for some reason so that would be a good thing to fix
6. new charge attack?
7. different types there could be a skeleton one a creeper one or even a spider one it doesnt make sense for there to only be a symbiont zombie.

ok cool thx

**Comment by Globalfirestorm10** [comment]
> ***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217
> 
> 
> 
> **Description of feature**
> 
> Describe what you want in the mod. Make sure this was not already suggested.
> 
> 
> 
> **ONLY ONE FEATURE REQUEST PER ISSUE**
> 
> I think the withered symbiont fight could be harder. If you have a diamond sword you can beat them easily. Cooldown for attacking the back so you cant combo and kill it immediatly. 
> 
> 
> 
> Ideas to make it harder
> 
> 
> 
> 1.  Cooldown for attacking the back so you cant combo and kill it immediatly. 
> 
> 2. wither storm does some more stuff during fight like shooting fireballs.
> 
> 3. maybe withered symbiont spawned phases 5-7 could be harder and bigger.
> 
> 4. more health cause it dies easily
> 
> 5. skeletons shoot the back for some reason so that would be a good thing to fix
> 
> 6. new charge attack?
> 
> 7. different types there could be a skeleton one a creeper one or even a spider one it doesnt make sense for there to only be a symbiont zombie.
> 
> 
> 
> ok cool thx
> 
>  

I like this idea, but I think that it should be toggleable, and there are some things to clarify/change here

1. I like this idea, but again, this, along with the other features need this to be toggleable

2. I'd probably say witherskulls instead of fireballs, which it already does normally

3. I don't get what you mean here. Do you think that symbionts should be spawned more? Or make them harder to beat the more the phases increase?

4. Again, idk what you mean here

5. This should be opened as a seperate issue as a filled out bug report, not in a suggestion

6. What do you have in mind?

7. IIRC, this was suggested already. I'm pretty sure that the symbiont is a combo of sickened mobs as well

**Comment by Globalfirestorm10** [comment]
This is just my opinion, feel free to ignore it, or not

**Comment by IndigoAmethyst** [comment]
Withered Symbionts only spawn phase 5.5 and after.

**Comment by IndigoAmethyst** [comment]
There is a cool down already in the mod that pushes you away from it.
