### ISSUE TITLE
Phase 2/3 Heads need to be hit less than phase 4+

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1186]
A minor change I fancied suggesting.

**Comment by darkheart78** [comment]
yeah

**Comment by sm644me** [comment]
I agree. Since the Wither Storm shoots so many skulls in those early phases (that the player can't avoid in the tractor beam), the player takes tons of damage compared to what phase 4+ will do. Making it a single blow would make escaping it more reasonable, especially with how little gear the player's intended to have that early on.

**Comment by BluePineappleGuy** [comment]
its also incredibly hard to hit the hitbox

**Comment by Aimyx** [comment]
i feel like this is intentional for giving the player a very big reason to run away, however it would give them a second chance if they thought it was as easy as a normal wither

**Comment by IndigoAmethyst** [comment]
Shoot I didn't mean to do that ರ⁠_⁠ರ

**Comment by BluePineappleGuy** [comment]
> Shoot I didn't mean to do that ರ⁠_⁠ರ

i know that feeling and i hate it

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
