### ISSUE TITLE
Tamed mobs with wither sickness should forget the player

### ISSUE THREAD

**Issue by ISLANDBANE** [nonamecrackers2/crackers-wither-storm-mod#1258]
since in Minecraft Story mode, there are 2 variants of wither sickness (one being gradual memory loss) i think tamed mobs should forget the player, the only way to get them back is by (like the current wither sickness) killing the wither storm.

**Comment by nonamecrackers2** [comment]
The only thing is that if mobs become untamed, the player may not necessarily notice that. All of sudden they could just see a wither sickened wolf (which would look like a wild one since it would become untamed), and could just pass off their pet not being there as it dying somehow. Maybe this wouldn't happen, but either way I'm not too keen on the idea of making pets losing their tamed status. Thanks for the suggestion though.
