### ISSUE TITLE
Make the wither storm evolve gradually instead of suddenly

### ISSUE THREAD

**Issue by HammedBurngur** [nonamecrackers2/crackers-wither-storm-mod#1267]
Instead of the wither storm suddenly changing phases I think it would be better if it had growth between phases

**Comment by TaintedBlock** [comment]
This kind of already exist

**Comment by LegendaryGodzilla** [comment]
I don't understand this lol

**Comment by HammedBurngur** [comment]
> I don't understand this lol

the wither storm would gradually grow instead of having 7 phases

**Comment by GearsawStudios** [comment]
> the wither storm would gradually grow instead of having 7 phases

This wouldn't work. Think of all the models needed for the growth and such, not to mention making it hard to indicate when the symbiote and hole can spawn. Simply put, it'd take too many resources for a small effect since you don't watch the Wither Storm the whole time. Most of the time, it evolves off screen, not to mention the lag of loading a new model so often.

**Comment by Composer-Hu** [comment]
If someone is willing to provide models and animations, I don't know if the cracker is willing to change it.

**Comment by nonamecrackers2** [comment]
#316

Not going to speak much about it, but I am aware of someone who is working on an addon mod that makes the Wither Storm's growth more dynamic (as in more blocks on the model are added as the storm eats more stuff)

**Comment by HammedBurngur** [comment]
Thanks for the reply. Don't mean to be rude with this question but if you
could would you?

**Comment by nonamecrackers2** [comment]
Well I don’t want to spoil what they’re working on, especially if they don’t want it shared yet
