### ISSUE TITLE
WitherStorm heads/tentacles turn white in the distance upon death animation

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1305]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
TITLE

**To Reproduce**
1. Go far away from WS
2. Kill WS
3. See ERROR

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
No

**Screenshots**
![2023-07-30_15 54 26](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/128298281/06ac481a-58da-4bb6-aff1-833c72873e47)

**Comment by nonamecrackers2** [comment]
What other mods you got installed?

**Comment by Steve982950** [comment]
well I have-

witherstormmod
worldedit
oculus
rubidium
mobbattle
starlight
ferritecore

**Comment by Steve982950** [comment]
also.. Please hurry for 1.20.1 before 1.20.2 comes out

**Comment by nonamecrackers2** [comment]
I will have to investigate

**Comment by Steve982950** [comment]
YESSIR!

**Comment by nonamecrackers2** [comment]
Was able to reproduce but not sure of a way to fix this issue. Appears to be a compatiblity issue with Oculus. This isn't game breaking since it only happens on the distant renderer, and you won't be viewing the death animation from a distance the majority of the time. You could possibly try reporting it to them to see if they have a fix.

**Comment by Steve982950** [comment]
oh my days....fine
