### ISSUE TITLE
Mobs are stored, rather than killed.

### ISSUE THREAD

**Issue by SuperSharkGaming** [nonamecrackers2/crackers-wither-storm-mod#1312]
Instead of killing a mob when the storm chomps it, you could add a custom dimension where there are a couple chambers that the mobs get stored in based on their [family=X] identifier, so they dont kill eachother. If the chambers are big enough, then the dimension could have a chunkloader (like the wither storm) so the mobs don't die from entity cramming and spread out in their chambers. 

the mobs could also be released from certain sections around the storm, based on their family identifier. (this could be done with a tag like "absorbed", so it separates the eaten mobs from the regular ones, preventing glitches like mobs teleporting everywhere for no reason.)

**Comment by nonamecrackers2** [comment]
Someone suggested something similar from what I remember however I cannot find it. Also, you don't specify when exactly mobs would be released.

Either way, I don't necessarily like the idea of storing all the mobs it consumes since that would be a lot of data to save (I have a different idea on saving them then what you're suggesting) and if they were to be resummoned, it would be a lot of entities and a lot of lag to do so. Thanks for your suggestion however.
