### ISSUE TITLE
[Bug]: Incompatibility with Aether: Symbiont repel aura and Tentacle reach are unpredictable and broken

### ISSUE THREAD

**Issue by sm644me** [nonamecrackers2/crackers-wither-storm-mod#1348]
### Minecraft Version

1.19.4

### Mod Version

3.2.1.3

### Mod Loader

Forge

### Mod Loader Version

45.1.0

### Describe the bug

When Aether and CWSM are installed together, CWSM gains two strange and inconsistent bugs.

First: The Withered Symbiont's repel aura (the effect that pushes the player away when casting a spell) sometimes is far stronger than intended. This is rare, but occasionally the player is launched very high and will likely die of fall damage. I've attached a screenshot below of one instance of this, but I've seen it launch the player much further before. This also happens in the Command Block fight, and the player will get stuck to the ceiling for anywhere from half a second to several seconds straight before they're dropped back down. This is most easily seen during the Symbiont's shulker bullet attack, but it looks like it can happen at any time. It might take several minutes for it to happen, or it might happen every time the player gets too close.

Second: Tentacles sometimes reach the player from very far away. In the Command Block fight, they sometimes hit the player from all the way across the arena. Again, this is inconsistent and can take a couple of minutes to happen, but it's very noticeable when it does. This can also happen when tentacles are spawned outside of the Command Block fight. I'm not sure how to screenshot this, but try it yourself, and you'll notice eventually.

This may be Aether's fault, but because CWSM is closed-source, I was told to report it here. Coordinating with the Aether devs might be a good way to diagnose and/or fix the problem. This wasn't an issue in Aether beta 4, if that helps.

### Steps to Reproduce

1. Install Aether (either the current beta version or, as of writing, the latest cutting-edge build) and CWSM
2. Summon a Wither Storm in phase 7 and progress the Command Block to phase 2 (this is not strictly related to the bugs, but it's the easiest place to test them)
3. Stay near the Withered Symbiont and note that the repel aura occasionally lasts for a very long time
4. Also note that tentacles occasionally hit the player from the opposite side of the arena

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![launch](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/133701211/3a70cd1a-e7e4-4e47-addb-dc088a5d6704)

### Mod List

Aether beta 5.1 & CWSM 3.2.1.3.

**Comment by TaintedBlockmObile** [comment]
Sm learned to fly in survival. That's really broken lol.

**Comment by nonamecrackers2** [comment]
Managed to reproduce, the repel aura appears to happen when I hit a mob (doesn't matter what mob). Looking into the cause now.

**Comment by nonamecrackers2** [comment]
I think I found the problem. When the bug occurs, all mobs (at least the symbiont and tentacles) visibility multiplier (the same thing that makes invisible targets have a shorter targeting range) goes up from 1 to 50, which increases it's targeting range *a lot*. This is why the tentacles can attack from so far occasionally, and since the symbionts aura uses essentially the same technology, this is also affected. This only happens when a mob is attacked though I've noticed, and after a bit it gets fixed.

I'd report this issue to them, and send them this [link](https://github.com/The-Aether-Team/The-Aether/blob/685f71c09a41804189eaf318f261f3c1e5b828b7/src/main/java/com/aetherteam/aether/event/listeners/abilities/AccessoryAbilityListener.java#L54C1-L69C6) since I believe this is where the problem is stemming from. I have no clue why this problem happens, which will be up to them to figure out.
