### ISSUE TITLE
[Bug]: Tainted logs can be crafted using tainted logs

### ISSUE THREAD

**Issue by CubeGamer647** [nonamecrackers2/crackers-wither-storm-mod#1426]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.46

### Describe the bug

The tainted log recipe in the withered beacon allows the input of one or more tainted logs, but tainted cobble and sand do not share this feature.

Side note, I feel the cobble and sand should allow their (non-tainted) variants. Should I make a suggestion ticket for that?

### Steps to Reproduce

1. Place tainted logs in a withered beacon alongside any amount of normal wood to add up to 6
2. Observe recipe works, only provides 1 tainted wood

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM
JEI

**Comment by nonamecrackers2** [comment]
Definitely unintended, shouldn’t be able to craft the tainted blocks with tainted blocks

**Comment by nonamecrackers2** [comment]
Looked into it, there isn't much I can do since the tainted log is in the `logs` tag which the recipe uses to determine if an item is a log that can be converted. I can remove the tainted log from the `logs` tag to fix this issue but it'd cause some compatibility issues with other recipes. This isn't a major issue so I'll be closing this.
