### ISSUE TITLE
[Suggestion]: New command block books instead of different tools

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1428]
### Desription of feature request

This is prob gonna get rejected but anyway

The idea is that instead of having wood, gold, iron, diamond, etc. command block tools, you could instead have 3 command block books that give different abilities to the tool you apply it to.

For a sword, it would work something like:
1. Impulse book - deals 11 damage but has high cooldown time
2. Repeating book - deals 6 damage but has extremely low cooldown time, essentially 1.8 pvp
3. Chain book - not exactly sure what this one can do but it could enhance the stats of the other 2

I know you mentioned that you wont be removing the new tools, but they still feel out of place so i thought this would be a better way of implementing versions with different stats

**Comment by TaintedBlockmObile** [comment]
How would you get these when you only have an impulse command block??

Also, the tools come with different abilities already. Which gives you options.

**Comment by CubeGamer647** [comment]
Tools aren't gonna get removed, but I like the idea of different enchantments. If different symbionts get added they could drop from those, but I'm not sure what they would do.

**Comment by nonamecrackers2** [comment]
This would still require removing the tools to replace it with this system (unless if you're suggesting that this is added on to the existing tools, which would just add a lot of unnecessary items), which is something I don't want to do since it'll kind of pointless adding a new feature then just removing it, making it look like we don't know what we are doing.

While the idea is interesting, we are going to be keeping the current tools for now. If the general consensus from everyone is that they don't like them, we'll remove them. For now if you have ideas on balancing the stats of the existing tools, please let us know in a new issue. Thank you.

**Comment by BluePineappleGuy** [comment]
> How would you get these when you only have an impulse command block??
> 
> Also, the tools come with different abilities already. Which gives you options.

the idea was to use all 3 command block variants, since a vanilla command block can create any of its variants it makes sense. 
i also thought it might fit more for progression, as the new tools make getting a diamond tool unnecessary when you can use an iron one instead.

anyway, as i predicted, it got closed, but if the general playerbase of the mod dislike the tools, crackers could do this instead.
