### ISSUE TITLE
[Suggestion]:  Follow up to #1356

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1454]
### Description of feature request

I have a idea that could work.

A option to where if a mob is targeted by a head the mob will take a small amount of damage (maybe just 1 hp), just so the mob will be aggressive towards the storm. This wouldn't affect mobs with less than 15 health in my opinion.

**Comment by Composer-Hu** [comment]
Smallest Slime: WTF you want? lol

**Comment by NinjaSam5399** [comment]
#1356 (Not Duplicate, just correcting the title)

**Comment by nonamecrackers2** [comment]
Looking over this again, this wouldn't really work well since the mob will not target the head (instead, the bottom of the Wither Storm's hitbox since that's how the targeting system is designed) and the mob may be too far away for them to actually target it. This is technically how mobs used to try to attack the Wither Storm but it didn't really work well, hence the overhaul in the latest update.
