### ISSUE TITLE
[Suggestion]: Emissive CMD Block Lights texture + toggle

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1459]
### Description of feature request

I am basically duplicating my own issue (#852) but I wanted to quickly respond to what's been answered:

> Explicit support with shader mods for the command block entity to render the emissive texture when shaders are enabled is a compatibility layer I do not want to implement, instead they would have to do something about this.

It doesn't really require a compatibility layer, it would be just neat if there was a togglable (off by default) extra texture file which only contains the lights, which will glow on the CMD block entity when turned on. Good for shader users. Idk if you changed your opinion about this since I first suggested it but idk yeah

**Comment by myron-obsolete-account** [comment]
I could also try to target the devs of the Complementary Shaders to add compatibility to this but it's extremely, insanely unlikely that they'll do something about it.

**Comment by nonamecrackers2** [comment]
Well there just needs to be support in general for blocks rendered outside of the normal world rendering to have emissive textures. I’m not sure how it works but since CWSM just re-renders the command block in the entity renderer (like TNT, chest and furnace minecarts) there shouldn’t be anything I’d need to do to make this work. This would mostly be a bandaid fix, it would be better for the shader mod to add support for this in general. Thanks for your suggestion though!
