### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Qee1y** [nonamecrackers2/crackers-wither-storm-mod#1579]
### Minecraft Version

1.19.2

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

43.3.2

### Describe the bug

I took out Command Block Sword in creative mode and the game didn't respond，Can only forcibly close the game。

[crash-2023-10-14_18.56.27-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12904649/crash-2023-10-14_18.56.27-server.txt)

### Steps to Reproduce

1.Take out the Command Block Sword
2.Place on the shortcut bar
3.Game Not responding！

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

:)

**Comment by IndigoAmethyst** [comment]
Firstly, you say you are playing on Minecraft 1.19.2, and CWSM 4.0.1, although that version of CWSM is only supposed to work with 1.19.4. 

Try using 1.19.4 instead as 4.0.1 is meant to be played with it.

**Comment by nonamecrackers2** [comment]
You've put 4.0.1 for the mod version which is for 1.20.1, the version should be 3.1.1.1 (as that's the version you're using in the crash report)

You could try removing these mods to see if it would fix the issue however (however no guarantee): `apotheosis, spelunkery, supplementaries, structure_gel, goodending, oculus, kiwi, ftblibrary, crafttweaker, shouldersurfing, puzzleslib, bookshelf, blueprint, moonlight, AdditionalAdditions, quark, irons_spellbooks`. If you find the cause of the issue, I'd report it to the author of whatever mod is causing it since it doesn't seem to be an issue with CWSM.

**Comment by Qee1y** [comment]
Sorry, I mistook the version
