### ISSUE TITLE
[Suggestion]: Lower all sounds when Withered Symbiont theme plays

### ISSUE THREAD

**Issue by MonKris** [nonamecrackers2/crackers-wither-storm-mod#1632]
### Description of feature request

During the Withered Symbiont fight, when the music is playing it would be a tiny bit nicer if all other sounds were lower so players wouldn't have to manually lower every single sound. (happened to me, and the tension of fighting a Withered Symbiont after "phase 2" would just disappear by slowly lowering the volume of almost everything because i wanted to listen to the banger soundtrack)

**Comment by BluePineappleGuy** [comment]
isn't the tension intended? after all, its a literal bossfight with a living sickened carcass magician.

**Comment by Aimyx** [comment]
that is the most literal description of a withered symbiote that any person
could ever come up with. Brilliant.

Anyway now i need someone to make a resource pack to make its name appear
as "Living Sickened Carcass Magician"

**Comment by BluePineappleGuy** [comment]
>Anyway now i need someone to make a resource pack to make its name appear as "Living Sickened Carcass Magician"

On it

**Comment by FalconinVoid** [comment]
This would be fr so nice! I hate it when the minecraft soundtrack kicks in a chase!

**Comment by FalconinVoid** [comment]
This would be fr so nice! I hate it when the minecraft soundtrack kicks in a chase!

**Comment by BluePineappleGuy** [comment]
> This would be fr so nice! I hate it when the minecraft soundtrack kicks in a chase!

It doesn't actually, the theme stops minecraft music from playing

**Comment by nonamecrackers2** [comment]
This idea is a bit suggestive since audio volume is a preference for each person. I wouldn't want this to become the standard that's in the mod since a lot of people would prefer to have the boss music turned down or off. I don't see the issue though in having the music discs slider (since that's what the boss music volume control is) at max while you lower all the other sliders a bit lower and just keep it that way.
