### ISSUE TITLE
[Bug]: Game lags horribly when mod is paired with Canary

### ISSUE THREAD

**Issue by FancyFella** [nonamecrackers2/crackers-wither-storm-mod#1710]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

I was testing mods for a potential 1.20.1 Modpack, and wanted both a Wither Storm Mod and a performance enhancing mod running at the same time, so I used Canary (version: 0.2.10). But whenever I played with both Wither Storm and Canary installed, it took about half a second for mob's movements to register, and blocks would reappear after breaking them.

### Steps to Reproduce

1. Install Wither Storm Mod and Canary 0.2.10
2. Play Minecraft
3. Observe mobs and/or try breaking a block that takes a while to break (like stone or sandstone)

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Canary 0.2.10

**Comment by ghost** [comment]
This is a known incompatibility in the wiki.
https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Known-Compatibility-Issues

Turn off Inject Custom AI Behavior in the config for the time being until this incompatibility gets resolved, or remove Canary.

**Comment by nonamecrackers2** [comment]
Canary used to automatically detect CWSM and apply the fix outlined [here](https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Known-Compatibility-Issues#lithium-forks-radium-canary-1182) but I guess it's not working anymore. What you need to do is add ``mixin.ai.nearby_entity_tracking=false`` to the ``canary.properties`` file in your config folder and reload the world, which should fix the lag.

As a side note, disabling "Inject Custom AI Behavior" is not necessarily a great idea since you get rid of all the mob fleeing mechanics and their ability to attack the Wither Storm back. Up to you if you'd like to disable however.
