### ISSUE TITLE
Add a tag for if an entity should use the Distant Rendering feature

### ISSUE THREAD

**Issue by Bloxxify2827** [nonamecrackers2/crackers-wither-storm-mod#1804]
### Description of feature request

The Wither Storm’s unique distant render feature is revolutionary in terms of rendering entities, it does something that no other mod has done, and it’d be useful if mod-makers could give entities the same desirable property like what the Wither Storm has. Giving or creating a tag that makes any entity assigned to it use the distant render feature would be useful for anybody looking to create a new entity, but have the same effect as the Wither Storm.

**Comment by Nov1st2k10** [comment]
would be better in its own mod (distant rendering api?)

**Comment by nonamecrackers2** [comment]
A tag wouldn't work since there's more that the entity needs to define in order to for it to distant render properly. Also, it would need to use the chunk loader system, which requires an extra set of parameters such as the chunk loading radius, etc. which can not be defined by tags themselves.

This feature would be more appropriate for a library mod, and it probably wouldn't be defined using tags but instead code through interfaces/registries.

**Comment by BluePineappleGuy** [comment]
> This feature would be more appropriate for a library mod, and it probably wouldn't be defined using tags but instead code through interfaces/registries.

small question, but are you going to make a library mod for it?
the distant renderer would be cool to see used in other mods

**Comment by nonamecrackers2** [comment]
I might, it’d probably be packaged in my already existing library mod CrackersLib
