### ISSUE TITLE
[Suggestion]: Make it more obvious that you can escape a chasing Wither Storm on foot

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1841]
### Description of feature request

Most people see how fast the Wither Storm is moving and assume they have to hide or live in the nether, thus never participating in chases. Perhaps make it more obvious that the Wither Storm can be outrun on foot regardless of speed, maybe in the Book and Quill inside the house?

**Comment by TaintedBlockmObile** [comment]
I think doing this would kind of ruin the element of surprise. You have to learn the behavior of the Wither Storm, not be taught how to beat it early on.

**Comment by GearsawStudios** [comment]
Yes, but not once have I seen someone realize it. I didn't even know until after beating the mod on Hardcore and had to be told that I could.

**Comment by sm644me** [comment]
I'm a bit conflicted on this one. There's three main factors to why.
1. Being directly told "hey, you can outrun it" alleviates a lot of the menacing aura that the Wither Storm has. In contrast, figuring it out on your own maintains the fear of "I don't know if this will work, but if it doesn't, I'm dead". To me, the big appeal of CWSM over other "apocalypse" mods is that terrifying feeling of being pursued by an unstoppable monster, not just that you're doing Survival with some other rules. Not knowing how it works or whether or not you're safe hugely contributes to that.
2. In typical CWSM gameplay, whether or not you're able to outrun it depends heavily on the terrain. Ocean? Sure, you're good. Plains or birch forest? Reasonably possible. Mountains and valleys? Nope, you need to hide now. Telling players to try and outrun it would likely lead to players getting bad terrain and being even more confused at why the mod's own advice "doesn't work". It also relies on equipment (arrows, invisibility potions, etc.) just in case you do get picked up. Even if you know you can outrun a chase, it's often a better decision anyway to hide underground.
3. I'm not Crackers, so I can't be sure about this, but it seems to me like CWSM is designed to support hiding underground and portalling away. The existence of Wither Sickness and the fact that the recipe got changed to need Magma Cream instead of a diamond implies to me that the "intended" strategy is to treat the mod like the old 404 challenge, with the added twist of Wither Sickness on the player and mobs. Just look at the fact that the bossbar and music go away underground now; I take that as strong evidence that spending plenty of time underground near it is intended.
I do enjoy doing chases, but I don't think that this is the way to go about it. I'm not sure what would be better, though.

**Comment by BluePineappleGuy** [comment]
This could be taught in the survival guide Crackers made rather than in the book and quill. Crackers would probably have to mention the bad terrain problem expressed above though.

**Comment by nonamecrackers2** [comment]
I'll echo a lot of what sm644me said. There's a lot of things I don't specifically tell people in the guide since I want them to discover and learn themselves through trial and error and this is one of those things. If players get good luck with terrain and figure this out, they should be able to seize that discovery which they uncovered on their own.
