### ISSUE TITLE
[Bug]: game crashes randomly after starting 

### ISSUE THREAD

**Issue by jackjackpdr** [nonamecrackers2/crackers-wither-storm-mod#1891]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

forge 47.2.21

### Describe the bug

from what i can see whenever i launch it gets to the menu i open the game and after 2 minutes it crashes and does it over and over and over and there is no exact reason why

### Crash Reports/Logs

error code 1 is the most i could find off of this

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/169451773/bb2ffc9f-d0ff-4461-a4fe-cbaac30aabc2)

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/169451773/cbe61d99-7e96-4462-a981-2adf5064dc11)

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/169451773/1f58f066-a5a8-485a-a1f7-a0e06b6a67e7)

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/169451773/1aa6db53-2430-48d0-bafc-62b3d6cc6485)

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/169451773/cd108d5e-2e85-4240-8ad7-1a04cc39ecf9)

**Comment by nonamecrackers2** [comment]
Please fill out the bug report form properly and provide the full crash report

**Comment by xelotex** [comment]
Hello! I'm having the same issue, seems to be because of a incompatibility with ModernFix and maybe Ferrite core but only when installed alongside ModernFix. 

Not really sure, the only thing i know is that when i stop loading the game with ModernFix installed, it stops crashing.

It didn't create any crash reports so I'll leave my log files here:
 
[debug.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/15279775/debug.log)
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/15279777/latest.log)

And i'll leave the mod list:
notenoughcrashes-4.4.7+1.20.1-forge.jar"
nyfsspiders-forge-1.20.1-2.1.1.jar"
ObsidianUI-forge-0.2.3+mc1.20.1.jar"
packetfixer-forge-1.3.2-1.19-to-1.20.1.jar"
paperdoll-forge-1.2.0-mc1.20.1.jar"
ParCool-1.20.1-3.2.1.2-R.jar"
piercearrow-1.20.1-5.0.0.jar"
PresenceFootsteps-1.20.1-1.9.1-beta.1.jar"
Prism-1.20.1-forge-1.0.5.jar"
PuzzlesLib-v8.1.18-1.20.1-Forge.jar"
qualitysounds-forge-1.5.0-1.20.1.jar"
radiantgear-forge-2.1.4+1.20.1.jar"
radium-mc1.20.1-0.12.3+git.50c5c33.jar"
Rrls-3.2.0-1.20.1-forge.jar"
rubidium-extra-0.5.4.3+mc1.20.1-build.121.jar"
RyoamicLights-forge-0.2.1+mc1.20.1.jar"
satisfying_buttons-1.0.0-1.jar"
saturn-mc1.20.1-0.1.3.jar"
Searchables-forge-1.20.1-1.0.2.jar"
secondchanceforge-1.20-1.5.1.jar"
Shields+-1.10.1-mc1.20.1.jar"
ShoulderSurfing-Forge-1.20.1-3.1.0.jar"
smoothboot(reloaded)-mc1.20.1-0.0.4.jar"
sniffsweapons-1.1.1-1.20.1 (1).jar"
sophisticatedbackpacks-1.20.1-3.20.5.1039.jar"
sophisticatedcore-1.20.1-0.6.18.597.jar"
sound-physics-remastered-forge-1.20.1-1.3.1.jar"
SpelunkersCharm-3.5.9-1.20.1.jar"
spyglass_improvements-1.5+mc1.20+forge.jar"
starlight-1.1.2+forge.1cda73c.jar"
structureessentials-1.20.1-3.3.jar"
TaxFreeLevels-1.3.10-forge-1.20.2.jar"
TES-forge-1.20.1-1.5.1.jar"
tia-1.20-1.1-forge.jar"
timecontrol-1.20.1-1.6.0.jar"
TimeStacker-forge-1.1.3-1.20.1.jar"
togenc-forge-1.20.x-v1.0.jar"
ToggledPickup-Forge-1.20.1-1.0.1-hotfix.jar"
ToolBelt-1.20-1.20.0.jar"
travelersbackpack-forge-1.20.1-9.1.13.jar"
TreeChop-1.20.1-forge-0.19.0.jar"
UniversalEnchants-v8.0.0-1.20.1-Forge.jar"
vanilla-refresh-1.4.19h.jar"
visuality-forge-2.0.2.jar"
walljump-1.20.1-1.0.1-forge.jar"
warriorrage-forge-1.20.1-1.0.1.jar"
waystones-forge-1.20-14.1.3.jar"
weaponmaster_ydm-forge-1.20.1-4.2.3.jar"
witherstormmod-1.20.1-4.1-all.jar"
Xaeros_Minimap_24.1.1_Forge_1.20.jar"
XaerosWorldMap_1.38.4_Forge_1.20.jar"
xercamod-1.20.1-1.0.0.jar"
YungsApi-1.20-Forge-4.0.4.jar"
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar"
YungsBetterDungeons-1.20-Forge-4.0.4.jar"
YungsBetterEndIsland-1.20-Forge-2.0.6.jar"
YungsBetterJungleTemples-1.20-Forge-2.0.4.jar"
YungsBetterMineshafts-1.20-Forge-4.0.4.jar"
YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar"
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar"
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar"
(1.20.1) - 3rdLife+ - 1.0.8.jar"
AI-Improvements-1.20-0.5.2.jar"
alexscaves-1.1.4.jar"
allurement-1.20.1-4.0.0.jar"
AmbientSounds_FORGE_v5.3.9_mc1.20.1.jar"
architectury-9.2.14-forge.jar"
artifacts-forge-9.5.1.jar"
AttributeFix-Forge-1.20.1-21.0.4.jar"
badpackets-forge-0.4.2.jar"
balm-forge-1.20.1-7.2.2.jar"
betterchunkloading-1.20.1-4.2.jar"
BetterF3-7.0.2-Forge-1.20.1.jar"
betterfpsdist-1.20.1-4.3.jar"
BetterTridents-v8.0.1-1.20.1-Forge.jar"
blueprint-1.20.1-7.0.3.jar"
BOMD-Forge-1.20.1-1.1.2.jar"
Bookshelf-Forge-1.20.1-20.1.10.jar"
caelus-forge-3.2.0+1.20.1.jar"
cavedust-2.0.4-1.20.1-forge.jar"
CerbonsAPI-Forge-1.20.1-1.1.0.jar"
citadel-2.5.4-1.20.1.jar"
clienttweaks-forge-1.20-11.1.0.jar"
cloth-config-11.1.118-forge.jar"
cofh_core-1.20.1-11.0.0.51.jar"
collective-1.20.1-7.57.jar"
Combatify 1.20 1.1.8.3 Forge (1).jar"
Controlling-forge-1.20.1-12.0.2.jar"
cosmeticarmorreworked-1.20.1-v1a.jar"
CreativeCore_FORGE_v2.11.24_mc1.20.1.jar"
cullleaves-forge-3.2.0 (1).jar"
cupboard-1.20.1-2.6.jar"
curios-forge-5.9.0+1.20.1.jar"
curiouslanterns-1.20.1-1.3.2.jar"
domesticationinnovation-1.7.1-1.20.1.jar"
Dungeon Crawl-1.20.1-2.3.14.jar"
dungeons-and-taverns-3.0.3.f[Forge].jar"
dynamic-fps-3.4.2+minecraft-1.20.4-forge.jar"
EasyAnvils-v8.0.2-1.20.1-Forge.jar"
EasyMagic-v8.0.1-1.20.1-Forge.jar"
eeeabsmobs-1.20.1-0.8.jar"
elenaidodge2-1.1.jar"
elytraslot-forge-6.3.0+1.20.1.jar"
elytrautilities-forge-2.2.1+1.20.1.jar"
embeddium-0.3.18+mc1.20.1-all.jar"
EnchantingInfuser-v8.0.2-1.20.1-Forge.jar"
EnchantmentDescriptions-Forge-1.20.1-17.0.14.jar"
endertrigon-1.20.1-1.0.jar"
endrem_forge-5.2.3-R-1.20.X.jar"
EnhancedAI-2.4.4-mc1.20.1.jar"
EnhancedVisuals_FORGE_v1.7.1_mc1.20.1 (2).jar"
ensorcellation-1.20.1-5.0.0.21.jar"
entity_model_features_forge_1.20.1-2.0.2.jar"
entity_texture_features_forge_1.20.1-6.0.1.jar"
entityculling-forge-1.6.2-mc1.20.1.jar"
extraplayerrenderer-1.20-1.0.0 (1).jar"
extrasounds-1.20.1-forge-1.3.jar"
Fallingleaves-1.20.1-2.1.0.jar"
Fastload-Reforged-mc1.20.1-3.4.0.jar"
feathers-1.1.jar"
FeederHelmet-47.1.0.jar"
ferritecore-6.0.1-forge.jar"
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar"
forgeskyboxes-0.0.2-1.20.2-new.jar"
geckolib-forge-1.20.1-4.4.4.jar"
geophilic-v2.2.0-mc1.20u1.20.2.jar"
gpumemleakfix-1.20.1-1.8.jar"
hardmodeores-1.20.1-b.jar"
hitindication-1.20.1-1.3.1 (1).jar"
hole_filler_mod-1.2.8_mc-1.20.1_forge.jar"
iceandfire-2.1.13-1.20.1-beta-4.jar"
Iceberg-1.20.1-forge-1.1.21.jar"
ImmediatelyFast-Forge-1.2.11+1.20.4.jar"
immersive_armors-1.6.1+1.20.1-forge.jar"
infernalmobs-1.20.1.2.jar"
infinitetrading-1.20.1-4.3.jar"
InsaneLib-1.13.4-mc1.20.1.jar"
inventorio-mc1.20.1-forge-v1.10.2.jar"
InvMove-1.20-0.8.4-Forge.jar"
ItemBorders-1.20.1-forge-1.2.1.jar"
ItemPhysic_FORGE_v1.7.1_mc1.20.1.jar"
jei-1.20.1-forge-15.3.0.4.jar"
jeiintegration_1.20.1-10.0.0.jar"
JustEnoughProfessions-forge-1.20.1-3.0.1.jar"
JustEnoughResources-1.20.1-1.4.0.247.jar"
KeepSomeInventory-v1.3.3.jar"
kotlinforforge-4.10.0-all.jar"
LegendaryTooltips-1.20.1-forge-1.4.5.jar"
letmedespawn-forge-1.20.x-1.2.0.jar"
lootbeams-1.20.1-1.2.5.jar"
lootintegrations-1.20.1-3.4.jar"
magictorchlamp-1.20.1-1.0.4.jar"
majrusz-library-forge-1.20.1-7.0.5.jar"
majruszs-difficulty-forge-1.20.1-1.9.9.jar"
make_bubbles_pop-0.2.0-forge-mc1.19.4+.jar"
MaxHealthFix-Forge-1.20.1-12.0.2.jar"
memoryleakfix-forge-1.17+-1.1.5.jar"
midnightlib-forge-1.4.2 (1).jar"
Mini-boss Boss Bars.jar"
modelfix-1.15.jar"
MouseTweaks-forge-mc1.20-2.25.jar"
MutantMonsters-v8.0.7-1.20.1-Forge.jar"
Mutants Buff 1.0.3 - 1.120.1.jar"
noisium-forge-2.0.3+mc1.20-1.20.1.jar"
notenoughanimations-forge-1.7.2-mc1.20.1.jar"

**Comment by jackjackpdr** [comment]
it was modernfix breaking my game 💀

**Comment by nonamecrackers2** [comment]
Yeah there's an issue with ModernFix currently, we're tracking it here: #1888
