### ISSUE TITLE
Wither Storm behavior slight changes

### ISSUE THREAD

**Issue by Asaredapvp2** [nonamecrackers2/crackers-wither-storm-mod#2016]
So basically, the Wither Storm could randomly stop eating the world and focus on consuming animals and mobs for some time.
This could especially help with performance during the 6-7 phases. Could be configurable in the settings if needed.

**Comment by TaintedBlock** [comment]
Ermm.. what

**Comment by Asaredapvp2** [comment]
Forgot to add that the Wither would also keep on trying to kill the player as well as other entities.

**Comment by LegendaryGodzilla** [comment]
bro is gonna become a tornado instead of a Wither Storm

**Comment by nonamecrackers2** [comment]
I'd rather not do this since it may seem weird during the larger phases why the Wither Storm has suddenly stopped picking stuff up. I think it's multitasking makes sense since the command block is theoretically doing all the heavy lifting with the block clusters while the wither itself is targeting and eating mobs.
