### ISSUE TITLE
[Suggestion]: Changing the position of the heads with config

### ISSUE THREAD

**Issue by Magiciandseq3** [nonamecrackers2/crackers-wither-storm-mod#2048]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

title explains

**Comment by Herobrine982950291** [comment]
Why would you want to change the position of the heads?

**Comment by TaintedBlock** [comment]
> Why would you want to change the position of the heads?

Resource packs that change the wither storm's model

**Comment by Magiciandseq3** [comment]
I making a resource pack and I changed ws models already but the head in the middle is too low

**Comment by nonamecrackers2** [comment]
This wouldn't be possible since the same head positions would need to be applied for all players in a server. That would also mean that they would all need the same resource pack, which some users may not want. In general it's best to leave the positions of the heads alone. While not ideal for resource pack people it will have to be a limitation that people will have to work around.
