### ISSUE TITLE
[Suggestion]: Bring back bowels cave ins, but only when the heads are defeated

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2124]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Once the bowels heads are defeated, the command block powering up sound plays and a "dragging" particle effect appears on the roof and goes downward as more and more clusters fall from the roof as a final act of "desperation" to stop its own death.

Also, when it is finally killed, the clusters that fall from the roof should be much bigger to add a dramatic effect

**Comment by Cod1ngGamer** [comment]
Great idea

**Comment by nonamecrackers2** [comment]
We toned down the clusters that fall due to it making it difficult to traverse the arena, this would just make it more difficult to move around. We could make it so that it would avoid areas where the player is, but this wouldn't help for when the player wants to move to other areas since there would be lots of blocks there.
