### ISSUE TITLE
suggestions regarding the WS

### ISSUE THREAD

**Issue by GoldenDarius** [nonamecrackers2/crackers-wither-storm-mod#223]
Several suggestions involving the body of the WS, mainly involved to the command block.

1.
The first thing I'd like to mention is a better way for mobs to get absorbed by the WS. When in his early stages, if a mob gets absorbed the hithox should be placed more close to the inside of the Command Block, as mobs die when they get close to it. I think it would make more sense if they would disappear by getting basically inside of it/in contact with it, same goes for the blocks it absorbs. When a mob/player is absorbed by the WS, rather than still playing their death animation with their body becoming red, the model just disappears similar to when frogs eat fireflies.

2.
This is connected to the next suggestion, the WS having an actual model of the Command Block inside of his giant forms, also being were the block end up going at, as well as the mobs and players. This can also be an actual hitbox that the WS can be greatly damaged at, giving some players (with the help of certain mods I suppose) to try and kill the WS by simply letting it pick them up so they can be picked up by the Command block and hit it, damaging the WS and also stopping the traction (similar to how it works with the heads). When the portal for the inside of the WS opens up, it could easily be directioned in the same placement of the actual physical Command block in the model. 

3.
The next suggestion is tied to the inside of the WS, which is making so that the dimension updates itself to add decorative "corpses" of mobs it has absorbed, similar to how it was shown in MC: SM. There could also be a function (maybe optional) for a player model to be spawned as decoration in case the WS has absorbed them. Another optional function that could be enabled or disabled from the settings can be the teleportation of players inside of the dimension when they are absorbed by the WS, basically "trapping" them there without the ability to really hurt the WS if they don't have the weaponry. Obviously they can just jump down from the hole to get out, or maybe it can be sealed for the time being they are there. I'd imagine this function to be nice in servers, in an hardcore mode one it could directly spawn a player model into the WS if they get killed by it.

4.
Last suggestion is for when the WS dies. When he is damaged by the F-Bomb, the WS will spawn slimy blocks of itself, so what if when the WS dies chunks of his body made out with that stuff falls down from the sky similar to Story Mode, which players can collect for building means? Maybe even a WS Head like the enderdragon one, or tentacles, both that can be picked up and used as decorations. Maybe this function can he disabled in the settings if a player just wants the WS to disappear.

**Comment by nonamecrackers2** [comment]
(I split up your suggestion into multiple easily distinguishable parts)

1. Slightly confused, I assume you meant to put "the head" instead of "the Command Block." While skipping the death animation is theoretically possible, I don't think It would be very noticeable and may have some unwanted side effects (however this is just speculation).

2. Are you saying that there should be a command block in the in it's mass model? If so I find this slightly redundant, as players can never see inside, and will probably never get inside (especially with the hitbox pushing players away). The player is also supposed to fight the Wither Storm via the bowels, not via melee attacks outside of it, defeating the purpose of the final boss fight, and again players will never reach it. I also don't want to features gated because you don't have a certain mod installed.

3. While making a corpse of each mob is excessive, this idea is interesting. I think it would make more sense to have mob heads statically generated with the structure and then have the WS keep track of players it killed and update the bowels tunnel with each player's head. I don't think trapping players inside the bowels is a practically good or fair idea, especially since if you die you'll never be able to get distance from it.

4. The chunks falling after death has been suggested and is confirmed: #184

I appreciate the suggestions however as always! (Let me know of anything I may have missed)

**Comment by GoldenDarius** [comment]
For the first point, I meant the early stages where the WS still is in is Wither Boss-looking forms. After watching again some game play of MC SM I noticed that the WS uses the tractor beam to get mobs and players close, then moves them underneath his head as they get absorbed, and I assume that's the placement of the Command Block. While for the smaller forms of the WS, I guess it would make sense to see the mobs touching the command block before disappearing. Last thing I'd like to mention is that I've seen the Engender Mod's WS do such thing as causing the death animation to not play, and in the recent versions of Minefraft they added frogs who actually do that with the mobs they consume (a video where frogs could eat any mob showed how they just disappear) which made me think that it was possible to simply use a similar code.
 Thank you for the patience to actually read our suggestion, we all appreciate it though
