### ISSUE TITLE
[Suggestion]: " Splash potion of Tainted "

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2289]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Throwing a Splash potion of tainted onto a normal block would turn that block into a tained block ( obv only on the blocks that has a tainted version )

**Comment by SSgamingYT** [comment]
Rather than "Splash potion of Taint", it could be "Sickened Bee Nectar", which, when used on a mob, instantly sets it to a late stage of wither sickness. If turned into a splash potion, it can turn blocks into their tainted variants, as well as give nearby mobs wither sickness. Drinking it (for whatever reason) gives you wither sickness and halves your health.

Obtained by "milking" a sickened bee while it hovers over a wither rose, using an empty bottle. This is difficult to do, as you have to catch it before it sees you (irl bees don't really care about the outside world when pollinating, so maybe that applies to sickened bees as well?)

This item would only work while the wither storm is alive, and upon the storm's death they turn back into standard honey bottles. (Including splash potions)

**Comment by BluePineappleGuy** [comment]
> Rather than "Splash potion of Taint", it could be "Sickened Bee Nectar", which, when used on a mob, instantly sets it to a late stage of wither sickness.

That would be pretty much the same as my tainted apple suggestion

**Comment by watersofnazareth** [comment]
You can actually do this using the mod's recipes, check the recipe for pumpkin tainting, Crackers doesn't want to add any additional effects currently
