### ISSUE TITLE
Command blocks, soul sand and wither skeleton skulls do not disappear immediately when a wither storm spawns

### ISSUE THREAD

**Issue by zChenX1** [nonamecrackers2/crackers-wither-storm-mod#23]
Maybe because of the instant lag when the wither storm spawns?
I think this is a small problem, I think it can be solved by simply optimizing the spawning decision of the first stage of the wither storm
![Uploading 2022-05-22_18.17.37.png…]()

**Comment by nonamecrackers2** [comment]
When the Wither Storm is first summoned it locates and prepares a "bowels" structure in the bowels dimension for the final boss fight., which causes the game to temporarily "freeze." The reason why it does it when it's summoned is because if it were to do it when you wanted to enter, the game would hang for a few seconds before you actually entered the bowels. The hang is removed by locating and prepping the bowels beforehand. I've tried looking at things right out of the box I could make better performance wise, however there isn't anything that stands out. I'll look into better improvements in the future, so for now I'll leave this open.

**Comment by zChenX1** [comment]
It turns out that, I wish your wither storm mod to find a solution in this regard as soon as possible!

**Comment by GrandmaPork** [comment]
Maybe make a bowels structure on world creation and any wither storm made after that would add a new one

**Comment by Catlord-3** [comment]
For removing the command block and soul sand, maybe wait something like 1 or 2 game ticks before generating the bowels? IDK if that is possible, but I think that would allow for the game to process that those blocks should be gone while still generating bowels on summon.

**Comment by RandomGithubUser32** [comment]
In my opinion, the best way to do this is to have the final boss arena generated when the invulnerability period of the wither storm ends.

**Comment by nonamecrackers2** [comment]
This will be fixed in the next major release
