### ISSUE TITLE
[Bug]: Issue with EMF animations 

### ISSUE THREAD

**Issue by Magiciandseq3** [nonamecrackers2/crackers-wither-storm-mod#2363]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Describe the bug

Issue with EMF animations when loading and unloading the Wither Storm in the distance

### Steps to Reproduce

 loading and unloading the Wither Storm in the distance
 With a Pack that changes animations of witherstorm

### Crash Reports/Logs

https://gist.github.com/Magiciandseq3/2600e21386e3e51f5fbd517879cbe1f9

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

EMF
ETF 
TGD
CWSM

**Comment by VillagerN4** [comment]
I will elaborate on the issue further.
The problem comes from animation variables.
They are not kept between the normal WS and the distant one. The normal WS resets variables everytime it is loaded, meanwhile the distant one, is keeping the variables no matter if it is loaded or not. It only pauses the animations when unloaded.
A fix to this issue would be adding EMF variable compatibility to the Storm by making it keep the variables between the two rendering ways.

**Comment by nonamecrackers2** [comment]
That isn’t really possible with how the two work. The distant wither storm always exists, even if it is not always rendered, and so the animation variables will never reset and will just pause when the distant wither storm stops rendering. When the normal one stops rendering, that version is destroyed and a new one is created when needed, resetting the animation variables. This is vanilla Minecraft entity behavior which is why I don’t think I can fix this, sorry.

This happens with the default tentacles and bugs me as well, but I can’t fix it due to this reason.
