### ISSUE TITLE
[Tractor beam passes through blocks] Small bug about wither storm's tractor beam

### ISSUE THREAD

**Issue by MrCoolz123456** [nonamecrackers2/crackers-wither-storm-mod#25]
I was playing around in minecraft creative but the wither storm's tractor beam passed through blocks and i thought it was weird so i decided to report it. Image:
![2022-05-23_15 41 52](https://user-images.githubusercontent.com/102673072/169769464-69397827-7287-49dd-b3e4-3e94b4cb25b5.png)

**Comment by nonamecrackers2** [comment]
This is unfortunately just how it works and there isn't a really solid way that I can think of at the moment to prevent this from happening. It's fine most of the time however. I'll leave this issue open for later me.

**Comment by myron-obsolete-account** [comment]
i have an idea: is it possible to split the tractor beam into about lets say 20 segments, and when one segment of the beam is inside a solid block, the tractor beam segments after the one thats in a block turn invisible and the particles get cut off there too? it might be causing the game to lag for phases where the storm has 9 heads, because every tractor beam segment would be checking for a solid block every tick, and that 9 times, meaning it would check for a solid block about 180 times in one second. thats 10800 times per minute 💀

**Comment by nonamecrackers2** [comment]
This has been partially fixed, the beam will no longer travel more than 10 blocks under blocks. There will still be some instances where it'll peak through terrain, but it should overall be a lot better.
