### ISSUE TITLE
Soundtrack and engender mod things

### ISSUE THREAD

**Issue by Seelk4dooM** [nonamecrackers2/crackers-wither-storm-mod#280]
Hello dev i have a suggestion, you can add more soundtracks that plays only if the wither storm is in x phase like the engender mod? (example: phase 5 plays the episode 3 theme) also can animate more the tentacles because they move slowly and make a command to kill the wither storm because im using your mod in a minecraft cinematographic series like netflix and for some scenes i need to put the wither storm and its like boring need to get inside him to destroy him and later respawn him for another scene, also add more movement and combat things to the wither storm like the engender mod because it feels more realistic and add a growth process i mean the wither storm big brain stills growing and growing without a limit and cover all the sky like engender mod. out of that Good job with the mod im very surprised! (sorry if some words u cant understand my english is bad and is not my native language)

**Comment by Gaboamau** [comment]
Let's see, first of all, the developer created the mod to resemble the Wither Storm from MC:SM as much as possible, but although it is true that it was inspired a bit by the Engender mod, it does not mean that it is a copy of it, because in the Engender mod when you spawn the WS, it starts destroying everything in its path without any particular objective, besides you can't survive it, since just by getting close, it kills you instantly, instead in MC:SM , the WS does have a target (that is you) and although it is true that it also destroys everything in its path, if you can fight it. Speaking about the soundtracks, it has already been suggested and if it is confirmed that it will be put, about the tentacles, the developer has already made them move faster and I think that as they are it is fine, and finally for the growth process more models would be needed, to which the developer said that he would not make any more models.

**Comment by Gaboamau** [comment]
It is also true that you have to take into account in which version of Minecraft you are playing, if you play in version 1.16.5, the developer said that there would be no more updates of things that will be added in the mod, only bug fixes and if you play in 1.18.2 or more, if things will be added.

**Comment by nonamecrackers2** [comment]
I'm not using the Engender mod as my reference. There is already a command to kill any entity (/kill), more soundtracks has already been suggested, and so has the tentacles (which has been declined). I also won't add infinite growth as I feel it covering the entire sky is a little over the top.
