### ISSUE TITLE
suggestions for the 1.19 version

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#361]
Ok so...

I have some features to suggest for the development of this mod. They're probably stupid but I've had them in my head for too long.

1st some small addition to the config which I think would fit perfectly:
a)No resistance if falling out of the bowels of the wither storm(set to false by default)
b)Instead of teleporting out of the bowels of the wither storm after destroying the command block you instead fall out making you watter bucket clutch or boat clutch(set to false by default)

The 2nd suggestion would be about the command block tools. Even though it was theorized that the tool intact survived it was later  confirmed that the command block tool was destroyed when the final hit on the command block was landed. Maybe you could implement it so the tool that lands the final hit on the command block would break after the said hit is landed, it could be turned off in the config ofc

The 3rd suggestion I have would be about the special beacon made with the Withered Nether Star. You can use 1 of these or all 2 of those. Or neither ig if you don't like them. 
a)Maybe it could have 1 more slot for an extra effect and double the range of a normal beacon. However if it's in a proximity of a normal beacon the range of that beacon is also increased.

b)Maybe it could kill hostile mobs within a 500 block radius around it that are above ground level(daytime spiders, neutral state endermen and zombie piglinz wouldn't count)

I'm not sure if Amy of these are even good but I hope I at least gave you some ideas

**Comment by nonamecrackers2** [comment]
The disabling fall resistance was already suggested: #340 

There is too much variability when it comes to players falling through the hole when dealing the final blow to the command block. Some players may still be in the bowels as the WS dies, which is why they are automatically teleported.

Making command block tools break was suggested here and I outlined my opinion on it: #356 

Still not sure on what I’m doing for the beacon but I plan on having it more extravagant than the ideas you suggested. Thanks for the suggestions though!
