### ISSUE TITLE
The Amulet can be found in the Rundown House and is linked to a specific Wither Storm from the start. The player who holds the Amulet is classified as the Ultimate Target. But this could also be disabled so that the player that spawns it is the Ultimate Target

### ISSUE THREAD

**Issue by Dark666Soul** [nonamecrackers2/crackers-wither-storm-mod#475]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**Comment by ghost** [comment]
amulet is only for multiplayer and i dont think it would be that necessary
and having the amulet linked to the wither storm will just be useless because its going to chase you anyway
amulet shouldnt spawn inside the house
your sopposed to write it down in the description

its 11 pm for me pls dont trash talk me for mispelling

**Comment by watersofnazareth** [comment]
The amulet is a server utility item not meant for non-server players

**Comment by nonamecrackers2** [comment]
> The amulet is a server utility item not meant for non-server players

This would also do pretty much the same thing as it already does. Also no Wither Storm exists when the world is generated so there would be no "specific Wither Storm from the start."
