### ISSUE TITLE
Storm Head improvements

### ISSUE THREAD

**Issue by Supertacoz** [nonamecrackers2/crackers-wither-storm-mod#479]
This isn't quite a feature request, but more so suggestions on what I think should be changed when it comes to the witherstorm's heads in phase 4 and beyond.

1. Head hitboxes: It seems the hitboxes for the left and right heads have funky hitboxes, as I can hit the middle head with a bow and arrow or sword with relative ease most of the time, but when I try to hit or shoot the left or right ones, the attacks almost always miss, despite aiming for the same spot as I would for the middle head. I could be in the jaws of one of the side heads, swinging my sword around like a madman, and still not hit it once. This makes it near impossible to reliably damage any of the heads picking you up.

2. Chain tractor beaming: another problem I've been having is that most of the time, as soon as I damage one head, one of the other ones immediately picks me up, and then the third one will immediately pick me up again, and by the time I've defeated the third head, the first will be back up again and pull me in, resulting in almost certain death. The main solution I propose for this issue is to make the other two heads ignore you for a short time (maybe a minute or two?) after you've damaged a head trying to pick you up.

**Comment by watersofnazareth** [comment]
#188, also 2 is going to be fixed and has been noticed

**Comment by nonamecrackers2** [comment]
1. You may be hitting the head, but the sound it plays to indicate as such isn't conventional and can go by unnoticed. Head injuring is also random for any of the heads. Also there shouldn't be any reason you'd miss, since you'd be pulled into the center of the hitbox and aiming anywhere would result in a hit. I'm planning on removing the randomness in the future.

2. This is also noticed and is going to be fixed.
