### ISSUE TITLE
Have block clusters fall when wither storm fake dies

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#598]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

During the fake death sequence in mcsm, Jessie had to navigate around an area filled with various tentacles and winding paths before he could climb up to the command block. I feel a good way to implement this is having various block clusters of various shapes and sizes, all made of flesh blocks, fall from the sky when the wither storm fake dies. They do not have heads attached, and as such do not come back to life when the wither storm is revived.

**Comment by Asteroid4** [comment]
I have another idea, should I make it in a new issue or share it here? It’s related to the segments during fake death.

**Comment by nonamecrackers2** [comment]
I originally wanted to do the tentacle maze-like structure seen in MCSM however considering the randomness of MC terrain and how the WS can be oriented in any direction instead of being locked on the four cardinal directions (which the block structure would be since they are technically blocks) I opted in for a starfish like structure elevated above the ground for easy access and to be able to adapt to any terrain (including the WS's orientation). While I could make random clusters fall from the WS, I can't guarantee where they would be placed, and I feel they would create awkward terrain that may look weird (especially considering that clusters kind of float because of their weird hitbox). They could be strategically placed, however I don't feel the work to implement this is in my best interest right now and I'll plan on leaving the play dead structure as it is. Thanks for the suggestions as always. And yes, if you have another idea that isn't correlated to this one, please make a new issue.
