### ISSUE TITLE
playing dead rework

### ISSUE THREAD

**Issue by personmhmyes** [nonamecrackers2/crackers-wither-storm-mod#611]
when the witherstorm is playing dead it there isnt much going on u just walk ontop on it to get to the command block
would could be done is its simular to mcsm which its more maze like with a couple random entities that are randomly picked exeptions being ender dragon, wither and all nether and end mobs just around it which will be simular to mcsm and 

once the command block is found it activates but doesnt revive the witherstorm immediantly and behaves like mcsm as in being active for a little pulling the player or a couple players/entities in the reviving

and when it rises the 3 storms rise with a delay being main always first then the 2 segments but 1 at a time with the delay period being really short from 1 second to 3 seconds

**Comment by nonamecrackers2** [comment]
My opinion on the maze-like structure: #598 

I don't want to add mobs that will annoy/distract player from getting to the command block, which is key. The command block does pull the player with a revive delay and I don't feel it should pull in other entities to really emphasize the fact that the Command Block is alive and it knows the player is there (not other mobs). For the last suggestion, I recommend making a separate issue for that since technically suggestion issues are only supposed to contain one request.
