### ISSUE TITLE
More Withered Symbiont Spells (just ideas)

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#612]
Idk if this counts as multiple features.

1: The withered symbiont shoots one flaming wither skull at the player.
2: The withered symbiont grabs blocks (makes copies of blocks if mob griefing is turned off) and throws them at the player. These break on contact and deal damage.
3: The withered symbiont shoots a purple beam at the player doing a bit of damage. If the beam hits the player, the wither storm will pick up the player if the player stuns a head, the wither storm stops, and the battle with the symbiont continues. In the final boss arena, under the condition that the beam hits the player, an unactivated wither storm head wakes up. This also wakes up heads that the player deactivated. 
4: Throws multiple potions with negative effects on the player with a shorter effect duration and gains a positive effect for a very short period of time. (Reference to Ivor)
5: The withered symbiont throws three dragon fireballs at the player. (area effect clouds straight up deal damage instead of giving entities instant damage)

**Comment by Catlord-3** [comment]
I like these ideas, but I feel like the beam one could be very annoying as it could be very hard to actually resume the fight, especially since the terrain where the wither storm is tends to get a bit tricky to navigate, and you could be dragged something like 75 blocks from the symbiont. other than that, I think these are really cool ideas, and it would be cool to see them be added to the mod.

**Comment by watersofnazareth** [comment]
Going to close this as 3 of these attacks have been implemented in some way, however if you want to suggest new attacks feel free to make new suggestions per idea, since having 1 issue with multiple points to it makes it so things never end up getting closed like this one
