### ISSUE TITLE
New potion From Story mode called "Elixir

### ISSUE THREAD

**Issue by KrukAdrian** [nonamecrackers2/crackers-wither-storm-mod#65]
So there was this potion in minecraft story mode that Ivor created in minecraft story mode. It would be cool if you added it and that if you throw it at the witherstorm it either dies or something else happens

**Comment by KrukAdrian** [comment]
I accidently made two of these oh no

**Comment by Gaboamau** [comment]
I have an idea of what that potion can do to the Wither Storm and it is that apart from the fact that it would only work in the initial phase, 1 and 2 because that is when the Command Block is exposed, what it could do is that it would deactivate the Command Block , turning the Wither Storm into a normal Wither, however its effect would be temporary meaning that if you don't defeat the Wither in time, the Command Block would activate again, turning back into the Wither Storm.

**Comment by Gaboamau** [comment]
If you defeat the Wither Storm when the Command Block is off, it will drop you a normal Nether Star and/or the Command Block. Although the idea seems good to me, in my opinion I do not recommend that you put it in the mod since in addition to the fact that this potion must be difficult to obtain, it takes away a bit of the sense of what is the progress of the fight against Wither Storm and its other phases.

**Comment by nonamecrackers2** [comment]
What Gaboamau said. Players will skip the majority of the mod and would make for a pretty lackluster experience. The potion never works in the game anyway and I think trying to include it in a way that would make sense right now isn't worth my time or what I envision the mod to be.

**Comment by Krypton6167** [comment]
welp even if it's not gonna be added I have a command for it:
/give @p minecraft:splash_potion{CustomPotionEffects:[{Id:6,Amplifier:28},{Id:18,Amplifier:9,Duration:2400}],CustomPotionColor:16766735,display:{Name:"\"Potion of Elixir\"",Lore:["A potion made by Ivor, can destroy any undead mob."]}}

**Comment by BluePineappleGuy** [comment]
i think maybe the elixir could instead deactivate the WS and turn it into its spawn totem. this is sort of a 'not yet i change my mind' thing. so if you don't think you're prepared enough for the WS, you can deactivate it and summon it again later. however only one would be in the spawn house and they're quite expensive to make (maybe smth like brewing a nether star into a potion of healing 2), and only act as a 1-time command block tool in the bossfight (i.e throwing the potion at the command block will make it lose a quarter of its health and activate the next stage of the bossfight).

**Comment by myron-obsolete-account** [comment]
> The potion never works in the game anyway

not to be that kind of person but it would have if they did it in time

I am such a 🤡

**Comment by Krypton6167** [comment]
Other command is outdated so here is your new /give witherstormmod:Elixer command:
/give @p minecraft:splash_potion{CustomPotionEffects:[{Id:6,Amplifier:28,Duration:-1,ShowParticles:0b},{Id:24,Duration:-1,ShowParticles:0b}],CustomPotionColor:16449300,display:{Name:"\"Elixer\"",Lore:["\"Ivor's potion, can kill any undead mob.\""]}}

**Comment by Krypton6167** [comment]
The other command is seemingly outdated, heres your new elixer command:
/give @p minecraft:splash_potion{CustomPotionEffects:[{Id:6,Amplifier:28,Duration:-1,ShowParticles:0b},{Id:24,Duration:-1,ShowParticles:0b}],CustomPotionColor:16449300,display:{Name:"\"Elixer\"",Lore:["\"Ivor's potion, can kill any undead mob.\""]}}

**Comment by Krypton6167** [comment]
ok this is just not working idk

**Comment by Aimyx** [comment]
Why are people still commenting here lol
