### ISSUE TITLE
Run down house not generating correctly

### ISSUE THREAD

**Issue by DTX3** [nonamecrackers2/crackers-wither-storm-mod#815]
This is my run down house at X: 0, Z: 0 coordinates. 

 I'm using 1.18.2

![IMG-0029](https://user-images.githubusercontent.com/59918994/209948720-be12841a-5511-4aaa-93ba-d78d891a0146.jpg)

Any ideas? Or how to fix it?

**Comment by ERCEpic** [comment]
My guy, that isnt the rundown house 💀

**Comment by nonamecrackers2** [comment]
What's your mod list?

**Comment by ERCEpic** [comment]
Bro forgot to put CWSM on the mod list

**Comment by DTX3** [comment]
> My guy, that isnt the rundown house 💀

Yep I noticed that :). This is what was at the at X: 0, Z: 0 coordinates.

Apologies. [Mod list](https://pastebin.com/D3rGaiAj)

I even tried clearing the space there and uninstalling and reinstalling, but the house never seems to generate, This is also installed on my server if it makes any difference.

**Comment by Globalfirestorm10** [comment]
> This is my run down house at X: 0, Z: 0 coordinates. 
> 
> 
> 
>  I'm using 1.18.2
> 
> 
> 
> ![IMG-0029](https://user-images.githubusercontent.com/59918994/209948720-be12841a-5511-4aaa-93ba-d78d891a0146.jpg)
> 
> 
> 
> Any ideas? Or how to fix it?
> 
> 

First off, this looks like a cut off witch hut, and you have yungs better witchhuts, so maybe it generation overlapped with the rundown house?
Also, i'm pretty sure there are incompatibilities with flat worlds

**Comment by DTX3** [comment]
Not sure why it wasn't generated. We're going to start a new server now anyways, so happy for this to be closed.

The mod works fine in my single-player world.

**Comment by myron-obsolete-account** [comment]
oh yeah i think i know what the issue is. if its a superflat world then the rundown house wont generate. and the reason why you found that whats in the screeenshot is maybe because some other structure (noticeable because there are candles at the edges) generated in there. if its not a superflat world then the rundown house might have been over-generated (first the house generated but then something else generated inside of it which made it disappear) but im not sure if thats the reason

**Comment by nonamecrackers2** [comment]
Can't really think of a specific mod that would cause this. You could try removing mods one by one to see what's the culprit however that's really tedious. I'll leave this open for future reference
