### ISSUE TITLE
Structure doesn't spawn in an already started world

### ISSUE THREAD

**Issue by Buno-B1** [nonamecrackers2/crackers-wither-storm-mod#832]
I had a vanilla minecraft world where i wanted to implement mods (All client side or vanilla friendly except of this one) and i ran into a problem: the Wither Storm structure doesn't spawn due to already loaded chunks. I just want to know if there's any option in the mod to reload the 0 ~ 0 chunk so the structure can spawn or if there's any solution to this, i dont know any method to reload or reset chunks.

**Comment by myron-obsolete-account** [comment]
structures wont generate when the place where they should be already has been generated, its not a bug. you could grab the world seed and recreate the world as a new one to then see the rundown house being generated too, but then you'd have to rebuild everything else. if your world has cheats enabled, i recommend getting the create mod, opening the schematics folder (you can go there by getting a schematictable in-game and then clicking the button open schematic folder)
to get the structure you need to go into the mod's files (try 7zip) and follow this path: 
Wither Storm Mod.jar\data\witherstormmod\structures\storm_spawn_platform.nbt
storm_spawn_platform.nbt is the structure. copy it and paste it in create's schematics folder, then go back to minecraft, take an empty schematic, upload it and place the structure (if you already have create and know how this works then im sorry for explaining)
if your world isnt with cheats on, you could temporarly enable a LAN multiplayer connection on your world (which probably wont work for you because you might not be connected with a LAN-cable to any other computer) and then you can enable cheats with that. to disable cheats, just rejoin the world

hope this helped

**Comment by Buno-B1** [comment]
I posted this has a question and not as a bug, i know that is something of the world/chunk generation of minecraft but maybe someone ran into the same issue puting it on an already existing world and could tell me how to fix it. I've already discover an other way to fix it that dont requires any mods and its easier to execute. i just needed to instal MCA Selector and delete the 0 ~ 0 chunks and the structure would spawn. Anyways, thank you for the help :)
