### ISSUE TITLE
game will crash on flat worlds on 1.19.2

### ISSUE THREAD

**Issue by Wither5575** [nonamecrackers2/crackers-wither-storm-mod#854]
**Minecraft version**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**
1. Go to flat world
2. Click on summon the wither storm at stage 7 and let the storm pick you up and the game will crash at least for me and i have a good pc so is not lag

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is Flywheel's optimizations active?**
Specify if Flywheel is installed and it's compat optimizations are enabled

**Screenshots**
!

**Comment by Wither5575** [comment]
![2023-01-14](https://user-images.githubusercontent.com/114622205/212480711-c4d7790d-6bdf-4d67-abca-640a4c0dfcf1.png)

**Comment by Wither5575** [comment]
crash report

**Comment by myron-obsolete-account** [comment]
this is a known issue where when you set your world generation type to anything else than default, modded dimensions wont load on world creation. you need to reload your world in order to make modded dimensions load in (the reason the game crashed when you summoned a wither storm is because it needs a place in the bowels dimension specified where the final boss fight should be, and without the dimension being loaded it cant generate the structures and crashes the game).

**Comment by Wither5575** [comment]
huh i was in the bowels on that world so thats weird

**Comment by myron-obsolete-account** [comment]
before or after the game crashed?

**Comment by Wither5575** [comment]
after

**Comment by Wither5575** [comment]
before i mean

**Comment by myron-obsolete-account** [comment]
thats weird.

**Comment by nonamecrackers2** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/843#:~:text=Reload%20the%20world%20after%20creating%20it
