### ISSUE TITLE
2 wither storm tentacle changes

### ISSUE THREAD

**Issue by NEWBOD007** [nonamecrackers2/crackers-wither-storm-mod#891]
1 (cubic tentacles) in story mode the the Wither storm tentacles have little cubes inside of them I thought would make it more like story mode and you can toggle it on or off via low-resolution model

2 (tentacle going through portal) in story mode (while escaping the Wither storm Jesse and his friends  go through nether portal and after a few seconds tentacle comes out of the portal and destroys it I want to make it if the Wither storm is near a portal with a player inside said dimension like nether or custom dimensions there will be a chance for the Wither storm's tentacles going through the portal and destroying it 

examples of cubic tentacles

https://youtube.com/clip/UgkxEh9KeNWBKFPK2FAU3BQnEHug8oepRpEq

example of tentacle going through a portal

https://youtube.com/clip/Ugkx5dqAcJIvfFwHp-v1YUguWQkGH1Zgtnaz

**Comment by FrozenDragon0** [comment]
Tentacles going through portals won't happen, pretty sure someone suggested something similar for the cubic tentacles though.

**Comment by myron-obsolete-account** [comment]
As FrozenDragon0 said, nonamecrackers2 already said that portal interactions won't be happening. I don't know what he said about the more detailed tentacles (probably that he doesn't want to edit WS models for now) but in my opinion they should stay like how they are now because the mod doesn't really aim for having a Wither Storm that looks exactly like the one in MCSM. It already feels like nonamecrackers2 himself invented the Wither Storm, and his mod has its own unique style of things, so I don't think detail changes for the tentacles would be neccessary. I personally like the current style of the tentacles a lot more than how detailed tentacles would look like, but my opinion doesn't matter anyways.

**Comment by GrandmaPork** [comment]
![Uploading 95A6A502-EC4A-44C8-AD39-8B980DD4F0C6.png…]()
 Tentacles are fine, they are like that in MCSM too

**Comment by myron-obsolete-account** [comment]
_**Other issues with same or similar topic/s:**_

---

>cubic tentacles

#169
#269
#306

---

>tentacle going through portal

#49
#248
#267

**Comment by myron-obsolete-account** [comment]
GrandmaPork your image doesn't seem to load.

**Comment by NEWBOD007** [comment]
okay I understand why cracker doesn't want to make tentacles go through portals but about the cubic tentacles it would look cooler on the Wither storm plus I am not suggesting to change the entire model just the tentacles

**Comment by watersofnazareth** [comment]
#217

**Comment by myron-obsolete-account** [comment]
haha knew it
