### ISSUE TITLE
Tentacle Movement

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#901]
Please Add That The Tentacles Move More Because That Would Look Better And Then People Would Stop Asking Me For The Tentacle Movement

And It Would Look Better

**Comment by myron-obsolete-account** [comment]
nonamecrackers2 already said no to that multiple times. according to his logic the tentacles should not move fast because it would make no sense for such a massive limb to swing this fast through the air, and i agree with his opinion. also, it would just feel kinda cringe for the tentacles to swing that fast. like a youtube kids video. sorry but thats how it is

so since this is a duplicate, please close this issue

**Comment by nonamecrackers2** [comment]
#47

Please check for duplicates before you open up a suggestion
