### ISSUE TITLE
Tainted Stone Tools

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#928]
**Description of feature**
![image](https://user-images.githubusercontent.com/53058491/219879636-2d42f816-27e3-4713-9027-76756875c26a.png)

I first wanted to suggest that you could just add crafting recipes to make normal stone tools (and wooden), but then I thought, why not tainted stone tools (and maybe wood too)??? They could have a bit more durability than the normal versions of the tools, and a little bit stronger too (since the original tainted blocks also take longer to mine).

**Comment by nonamecrackers2** [comment]
I don't really want to add another tool set, especially since these tools will only be slightly better than stone/wood and can only be crafted when you're in the bowels (with much better gear), not seeing much use. I believe in the upcoming update the stone/wood can be used to make the normal wood/stone tools however.

**Comment by myron-obsolete-account** [comment]
Understandable, have a nice day.
