### ISSUE TITLE
Can't Hit The Tentacle In VR

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#970]
When I Play In VR I Can't Hit The Wither Storm Tentacle In The Bowels

Version = 1.18.2

**Comment by myron-obsolete-account** [comment]
Which tentacle tho.

**Comment by LucasDotje** [comment]
I Said Bowels Tentacle

**Comment by Globalfirestorm10** [comment]
I believe there are many incompatibilies for vivecraft due to the nature of the mod. I assume you are using vivecraft and the latest version of CWSM, right? It's hard to know, as you've not only provided zero information on this issue, but also completely deleted the PRE MADE template we provide you each bug report. For now on, when you are reporting a bug, please abide by the guidlines, which includes **FILLING OUT THE GODDAMN TEMPLATE**

**Comment by Globalfirestorm10** [comment]
While you can _not_ fill out the template, it is recommended you do so, as people may be able to assist you easier. Just don't expect someone to immediately know whats wrong when you don't fill out the template

**Comment by myron-obsolete-account** [comment]
> I Said Bowels Tentacle

There are like 16 tentacles, you need to specify if you mean one of the tentacles that are everywhere on the ground in the boss fight area or the ones that are on the small "island", as I like to call it.

**Comment by nonamecrackers2** [comment]
Was able to reproduce, however from testing I don't think there is a way to easily fix this on my end.

**Comment by Bloxxify1520** [comment]
> Was able to reproduce, however from testing I don't think there is a way to easily fix this on my end.

Possibly a larger tentacle hitbox?

**Comment by Bloxxify1520** [comment]
Or a specific version for vivecraft that makes hitboxes larger, enabling you to hit them more easily

**Comment by V0calgiant12** [comment]
When I did a playthrough, I was able to hit them just fine without using the trigger
